Fix reload issues and ObsBadge match error
gemini-hlsw/explore pull request #1698
Opened 2022-04-13 19:03 UTC by toddburnside

The value inside of `SelectedPanel.Editor(value)` is no longer used. The state update came too late and was causing problems because the editor was being rendered based on old values. On the target tab, this could result in the URL being "rewritten" by the AsterismEditor. Now the focused obs/target values from props are used directly. `SelectedPanel` can be cleaned up and simplified, but I wanted to get this PR into staging because it fixes problems. I will clean up `SelectedPanel` and `TwoPanelState` in a separate PR.

2022-04-13 20:03 UTC, cquiroz approved these changes
LGTM

2022-04-13 20:47 UTC, rpiaggio requested changes
As a general rule we shouldn't define components dynamically. If we do, it should be done once and store the resulting component for future use (like we do with context/state providers and tables).

In this case, although using reusability avoids rerendering with a new component definition during the lifetime of the parent, a new component is defined whenever the parent remounts. If we need to pass to the component things that change during runtime we probably want to unify this through the mechanism of component properties.

This was part of the reason for substituting ReactTableHelpers with direct usage of the controls.

2022-04-13 21:17 UTC, toddburnside commented
> As a general rule we shouldn't define components dynamically. If we do, it should be done once and store the resulting component for future use (like we do with context/state providers and tables).
> 
> In this case, although using reusability avoids rerendering with a new component definition during the lifetime of the parent, a new component is defined whenever the parent remounts. If we need to pass to the component things that change during runtime we probably want to unify this through the mechanism of component properties.
> 
> This was part of the reason for substituting ReactTableHelpers with direct usage of the controls.

Hmmm. I see. I guess I can rewrite the LiveQueries into more complex components so they can take the program id as a property value as well as the `A => VdomNode`.

2022-04-13 23:46 UTC, merged

2022-04-14 21:59 UTC, rpiaggio reviewed
LGTM :+1: Thank you. I know this is merged already, but just in case ;)